---
- name: install haproxy
  yum:
    name: haproxy
    state: present

- name: change SE linux settings
  replace: dest='/etc/selinux/config'
    regexp='SELINUX=enforcing'
    replace='SELINUX=permissive'

- name: update HAProxy config
  template: src=templates/haproxy.cfg 
    dest=/etc/haproxy/haproxy.cfg 
    backup=yes