---
- name: install haproxy
  yum:
    name: haproxy
    state: present

- name: change SE linux settings
  shell: semanage port -m -t http_port_t -p tcp 8081
  # change to frontend port

- name: update HAProxy config
  template: src=templates/haproxy.cfg 
    dest=/etc/haproxy/haproxy.cfg 
    backup=yes