- hosts: localhost # change hosts file to include relevant hosts
  become: yes
  
  # edits haproxy config file with new data
  vars:
    haproxy_mode: http # default
    haproxy_algorithm: roundrobin # default
    haproxy_frontend: localhost:8081 # change to frontend root URL

  roles:
    - database # pull jenkins info from JSON
    - haproxy # install haproxy, update config file with variables